### ISSUE TITLE
Structure visualisation error

### ISSUE THREAD

**Issue by reemelkabbout** [geraldinepascal/FROGS#49] opened 2020-06-22 13:35 UTC
Hey everyone ! I hope you're doing well.

Could anyone explain to me why I'm getting this error during the FROGSSTAT Phyloseq Structure Visualisation step? Is it because of an inconsistency between the coordination method and the distance matrix?
![FROGS Error](https://user-images.githubusercontent.com/64663787/85293578-3d0c2b80-b4a6-11ea-9e75-b9588840aaa6.JPG)
I tried all the distance matrixes but I got the same error. 
Thank you,

**Comment by mariabernard** [comment] 2020-06-22 13:44
Hi!

R error messages are not wrapped in the FROGSSTAT tools. So the message you sent is useless.
Could you send me a screenshot of the parameter settings?

**Comment by mariabernard** [comment] 2020-06-22 13:57
As I said privetly, it's much better to contact the support team of the Galaxy server you used. If the problem is due to a dependency installation, they could rerun the subcommand lunch by the tool and recover a more understandable message. If not it's important to indicate whate are your input files.

As this will be deal with us on one of our servers, I close this issue

**Closed as completed by mariabernard** 2020-06-22 13:57 UTC
